### ISSUE TITLE
"Cannot read property 'toString' of undefined" when using dot notation on "field" option

### ISSUE THREAD

**Issue by hems** [budiadiono/mongoose-slug-hero#3]
i'm getting an error when defining the slug field with "." notation, for instance `field: 'info.title'`

```
   TypeError: Uncaught error: Cannot read property 'toString' of undefined
  at slug (/Volumes/backpack/git/loopcast/killer/node_modules/slug/slug.js:13:20)
  at model.<anonymous> (/Volumes/backpack/git/loopcast/killer/node_modules/mongoose-slug-hero/lib/mongoose-slug-hero.js:105:10)
[...]
```

the problem comes from the fact that you check for the property with "_this[slugField]" which won't translate well in case there is a "." on the field.

**Comment by hems** [comment]
i guess same will happen to slugField

**Comment by budiadiono** [comment]
Hi, thanks for reporting this issue. I'll investigate it soon.

**Comment by budiadiono** [comment]
You were right that `_this[slugField]` was causing the issue. I've just make fix for that, please let me know if it still doesn't work for you. Thanks for the clue! :)

**Comment by hems** [comment]
could you please publish a new version to npm so i can update my package.json and hopefully get it sorted?

**Comment by budiadiono** [comment]
Sure, let me double check everything first before making this release.

**Comment by budiadiono** [comment]
Done, it is published now.

**Comment by hems** [comment]
all good, perfect

**Comment by hems** [comment]
thx!
:8ball:

**Comment by budiadiono** [comment]
You're welcome! :)
